_wandb:
    value:
        cli_version: 0.19.8
        code_path: code/train.py
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 64
epochs:
    value: 10
gamma:
    value: 0.99
lr:
    value: 1.1451870291458343e-05
target_type:
    value: mc
weight_decay:
    value: 3.6130734592932116e-06
